---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  user: prad
  sudo: yes

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: web
  user: prad
  sudo: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: db
  user: prad
  sudo: yes

  roles:
    - db

- name: install git
  hosts: app
  user: prad
  sudo: yes

  roles:
    - app
