---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  user: prad
  sudo: yes

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: prad
  sudo: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: prad
  sudo: yes

  roles:
    - db
